routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// SITIO
Route::group([
    'as' => 'sitio.',
    // 'middleware' => 'auth',
], function() {

    Route::get('/', 'SitioController@index')->name('index');
    Route::get('/offline', 'SitioController@offline')->name('offline');
    Route::get('/prestamos', 'SitioController@prestamos')->name('prestamos');
});

// PRESTAMOS
Route::group([
    'as' => 'prestamos.',
    'prefix' => 'prestamos',
    'middleware' => 'auth',
], function() {

    Route::get('create', 'PrestamoController@create')->name('create');
    Route::post('store', 'PrestamoController@store')->name('store');
});

// ADMIN
Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
], function() {

    Route::get('', 'AdminController@index')->name('index');

    // ADMIN LIBROS
    Route::group([
        'prefix' => 'libros',
        'as' => 'libros.',
    ], function() {

        Route::get('', 'LibroController@index')->name('index');
        Route::get('create', 'LibroController@create')->name('create');
        Route::post('', 'LibroController@store')->name('store');
        Route::get('{id}/edit', 'LibroController@edit')->name('edit');
        Route::put('{id}', 'LibroController@update')->name('update');
        Route::get('{id}', 'LibroController@show')->name('show');
        Route::delete('{id}', 'LibroController@destroy')->name('destroy');
    });

    // ADMIN AUTORES
    Route::group([
        'prefix' => 'autores',
        'as' => 'autores.',
        'middleware' => 'auth',
    ], function() {

        Route::get('', 'AutorController@index')->name('index');
        Route::get('create', 'AutorController@create')->name('create');
        Route::post('', 'AutorController@store')->name('store');
        Route::get('{id}/edit', 'AutorController@edit')->name('edit');
        Route::put('{id}', 'AutorController@update')->name('update');
        Route::get('{id}', 'AutorController@show')->name('show');
        Route::delete('{id}', 'AutorController@destroy')->name('destroy');
    });

    // ADMIN PERSONAS
    Route::group([
        'prefix' => 'personas',
        'as' => 'personas.',
        'middleware' => 'auth',
    ], function() {

        Route::get('', 'PersonaController@index')->name('index');
        Route::get('create', 'PersonaController@create')->name('create');
        Route::post('', 'PersonaController@store')->name('store');
        Route::get('{id}/edit', 'PersonaController@edit')->name('edit');
        Route::put('{id}', 'PersonaController@update')->name('update');
        Route::get('{id}', 'PersonaController@show')->name('show');
        Route::delete('{id}', 'PersonaController@destroy')->name('destroy');
    });

    // ADMIN COLA
    Route::group([
        'prefix' => 'cola',
        'as' => 'cola.',
    ], function() {

        Route::get('', 'ColaController@index')->name('index');
        Route::post('', 'ColaController@store')->name('store');
        Route::delete('{idLibro}/{idPersona}', 'ColaController@delete')->where([
                                                                           'idLibro' => '[0-9]+',
                                                                           'idPersona' => '[0-9]+',
                                                                       ])->name('delete');
        Route::delete('{idLibro}/limpiar', 'ColaController@limpiarCola')->name('limpiar');
    });
});

// API
Route::group([
    'prefix' => 'api',
], function() {

    // API PRESTAMOS
    Route::group([
        'prefix' => 'prestamos',
    ], function() {

        // Ajax
        Route::get('pendientes', 'PrestamoController@apiPendientes');
        Route::put('{id}', 'PrestamoController@apiUpdate');
        Route::delete('{id}', 'PrestamoController@apiDelete');

        Route::put('{id}/marcar-entregado', 'PrestamoController@apiMarcarEntregado');
    });

    // API AUTORES
    Route::group([
        'prefix' => 'autores',
        'namespace' => 'Admin',
    ], function() {

        // Ajax
        Route::get('todos', 'AutorController@apiTodos');

    });
});


Auth::routes();

resources/views/admin/index.blade.php
@extends('admin.layout')
@section('titulo', 'Administración')
@section('contenido_admin')
  <div class="container my-5">

    <div class="d-flex justify-content-around flex-wrap">

        <a href="{{ route('admin.libros.create') }}"
           class="text-decoration-none my-2 mx-1">
          <div class="atajo text-dark">
            <i class="fa fa-book"></i>
            <span>Crear Libro</span>
          </div>
        </a>

        <a href="{{ route('admin.personas.create') }}"
           class="text-decoration-none my-2 mx-1">
          <div class="atajo text-dark">
            <i class="fa fa-user"></i>
            <span>Crear Persona</span>
          </div>
        </a>

        <a href="{{ route('admin.autores.create') }}"
           class="text-decoration-none my-2 mx-1">
          <div class="atajo text-dark">
            <i class="fa fa-user-tie"></i>
            <span>Crear Autor</span>
          </div>
        </a>
    </div>

  </div>
@endsection
@push('scripts')
  <script>
    $('.nav-link-escritorio').addClass('active');
  </script>
@endpush

resources/views/admin/layout.blade.php
@extends('layouts.app')
@section('contenido')
  <div class="container">

    @auth
    {{--cerrar sesión--}}
    <div class="text-right w-100">
      <a class="" href="{{ route('logout') }}"
         onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
          <i class="fa fa-sign-out-alt fa-sm"></i>
      </a>
      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
          @csrf
      </form>
    </div>

    <ul class="nav nav-tabs justify-content-center">
      <li class="nav-item">
        <a class="nav-link nav-link-escritorio" href="{{ route('admin.index') }}">
          <i class="fa fa-tachometer-alt"></i>
          Escritorio
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link nav-link-libros" href="{{ route('admin.libros.index') }}">
          <i class="fa fa-book"></i>
          Libros
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link nav-link-personas" href="{{ route('admin.personas.index') }}">
          <i class="fa fa-user"></i>
          Personas
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link nav-link-autores" href="{{ route('admin.autores.index') }}">
          <i class="fa fa-user-tie"></i>
          Autores
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link nav-link-cola" href="{{ route('admin.cola.index') }}">
          <i class="fa fa-tasks"></i>
          Cola
          @if ($LibroDisponibleConCola)
            <span class="text-success"><b>*</b></span>
          @endif
        </a>
      </li>
    </ul>
    @endauth

    @yield('contenido_admin')

  </div>
@endsection