routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// SITIO
Route::group([
    'as' => 'sitio.',
    // 'middleware' => 'auth',
], function() {

    Route::get('/', 'SitioController@index')->name('index');
    Route::get('/offline', 'SitioController@offline')->name('offline');
    Route::get('/prestamos', 'SitioController@prestamos')->name('prestamos');
});

// PRESTAMOS
Route::group([
    'as' => 'prestamos.',
    'prefix' => 'prestamos',
    'middleware' => 'auth',
], function() {

    Route::get('create', 'PrestamoController@create')->name('create');
    Route::post('store', 'PrestamoController@store')->name('store');
});

// ADMIN
Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
], function() {

    Route::get('', 'AdminController@index')->name('index');

    // ADMIN LIBROS
    Route::group([
        'prefix' => 'libros',
        'as' => 'libros.',
    ], function() {

        Route::get('', 'LibroController@index')->name('index');
        Route::get('create', 'LibroController@create')->name('create');
        Route::post('', 'LibroController@store')->name('store');
        Route::get('{id}/edit', 'LibroController@edit')->name('edit');
        Route::put('{id}', 'LibroController@update')->name('update');
        Route::get('{id}', 'LibroController@show')->name('show');
        Route::delete('{id}', 'LibroController@destroy')->name('destroy');
    });

    // ADMIN AUTORES
    Route::group([
        'prefix' => 'autores',
        'as' => 'autores.',
        'middleware' => 'auth',
    ], function() {

        Route::get('', 'AutorController@index')->name('index');
        Route::get('create', 'AutorController@create')->name('create');
        Route::post('', 'AutorController@store')->name('store');
        Route::get('{id}/edit', 'AutorController@edit')->name('edit');
        Route::put('{id}', 'AutorController@update')->name('update');
        Route::get('{id}', 'AutorController@show')->name('show');
        Route::delete('{id}', 'AutorController@destroy')->name('destroy');
    });

    // ADMIN PERSONAS
    Route::group([
        'prefix' => 'personas',
        'as' => 'personas.',
        'middleware' => 'auth',
    ], function() {

        Route::get('', 'PersonaController@index')->name('index');
        Route::get('create', 'PersonaController@create')->name('create');
        Route::post('', 'PersonaController@store')->name('store');
        Route::get('{id}/edit', 'PersonaController@edit')->name('edit');
        Route::put('{id}', 'PersonaController@update')->name('update');
        Route::get('{id}', 'PersonaController@show')->name('show');
        Route::delete('{id}', 'PersonaController@destroy')->name('destroy');
    });

    // ADMIN COLA
    Route::group([
        'prefix' => 'cola',
        'as' => 'cola.',
    ], function() {

        Route::get('', 'ColaController@index')->name('index');
        Route::post('', 'ColaController@store')->name('store');
        Route::delete('{idLibro}/{idPersona}', 'ColaController@delete')->where([
                                                                           'idLibro' => '[0-9]+',
                                                                           'idPersona' => '[0-9]+',
                                                                       ])->name('delete');
        Route::delete('{idLibro}/limpiar', 'ColaController@limpiarCola')->name('limpiar');
    });
});

// API
Route::group([
    'prefix' => 'api',
], function() {

    // API PRESTAMOS
    Route::group([
        'prefix' => 'prestamos',
    ], function() {

        // Ajax
        Route::get('pendientes', 'PrestamoController@apiPendientes');
        Route::put('{id}', 'PrestamoController@apiUpdate');
        Route::delete('{id}', 'PrestamoController@apiDelete');

        Route::put('{id}/marcar-entregado', 'PrestamoController@apiMarcarEntregado');
    });

    // API AUTORES
    Route::group([
        'prefix' => 'autores',
        'namespace' => 'Admin',
    ], function() {

        // Ajax
        Route::get('todos', 'AutorController@apiTodos');

    });
});


Auth::routes();

app/Cola.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Persona;
use App\Libro;

class Cola extends Model
{
    protected $table = 'cola';

    protected $fillable = [
        'persona_id',
        'libro_id',
    ];

    protected $primaryKey = [
        'persona_id',
        'libro_id',
    ];

    public $incrementing = false;

    public function persona()
    {
        return $this->belongsTo(Persona::class);
    }

    public function libro()
    {
        return $this->belongsTo(Libro::class);
    }

    static function hayLibrosDisponibles()
    {
        foreach (self::all() as $registro) {
            if ($registro->libro->estaDisponible) return true;
        }
        return false;
    }

}

app/Http/Controllers/Admin/ColaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Cola;
use App\Libro;

class ColaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('store');
    }

    public function index()
    {
        $registrosBD = Cola::with('libro')->get()->sortByDesc('libro.estaDisponible');

        $registros = [];

        foreach ($registrosBD as $reg) {
            $registros[$reg->libro_id] = (object)[
                'libro' => Libro::find($reg->libro_id),
                'cola' => Libro::find($reg->libro_id)->cola
            ];
        }

        return view('admin.cola.index', compact('registros'));
    }

    public function store(Request $request)
    {
        $input = $request->validate([
            'persona_id' => 'required|exists:personas,id',
            'libro_id' => 'required|exists:libros,id'
        ]);

        try {
            Cola::create($input);
        } catch (\Exception $ex) {
            if (strpos($ex->getMessage(), 'Duplicate entry') > -1) {
                throw new \Exception('Ya se encuentra el cola para este libro');
            }
        }

        return response()->json([
            'mensaje' => 'Se agregó a la cola satisfactoriamente. El administrador de la biblioteca lo tendrá en cuenta cuando el libro esté disponible.',
        ]);

    }


    public function delete(Request $request, $idLibro, $idPersona)
    {
        // $input = $request->validate([
        //     'persona_id' => 'required|exists:personas,id',
        //     'libro_id' => 'required|exists:libros,id'
        // ]);

        Cola::where([
            'persona_id' => $idPersona,
            'libro_id' => $idLibro
        ])->delete();

        $feedback = [
            'tipo' => 'success',
            'texto' => 'Se borró la persona de la cola satisfactoriamente',
            'titulo' => 'Éxito',
        ];

        return redirect()->route('admin.cola.index')
                         ->with('feedback', $feedback);
    }

    public function limpiarCola(Request $request, $idLibro)
    {
        Cola::where('libro_id', $idLibro)->delete();

        $feedback = [
            'tipo' => 'success',
            'texto' => 'Se limpió la cola satisfactoriamente',
            'titulo' => 'Éxito',
        ];

        return redirect()->route('admin.cola.index')
                         ->with('feedback', $feedback);

    }
}

resources/views/admin/cola/index.blade.php
@extends('admin.layout')
@section('titulo', 'Cola de Préstamos')
@section('contenido_admin')
  <div class="container my-3">

    <h1 class="text-center">Cola de Préstamos</h1>

    @foreach($registros as $registro)
      <div class="libro my-3 border rounded p-1">

        @if ($registro->libro->estaDisponible)
          <span class="badge badge-pill badge-success float-right">Libro Disponible</span>
        @endif

        <div class="d-flex justify-content-between">
          <div>
            <p>
              <span class="text-muted">Libro:</span>
              <br>
              <div class="d-flex align-items-center">
                  <a href="{{ route('admin.libros.show', $registro->libro->id) }}" class="text-reset mr-1">
                    <img src="{{ $registro->libro->imagen }}" width="40">
                  </a>
                  <a href="{{ route('admin.libros.show', $registro->libro->id) }}" class="text-reset">
                    <h5>
                      {{ $registro->libro->nombre }} <br/>
                      <span>
                        <small>
                          (@foreach($registro->libro->autores as $autor)
                            {{ $autor->nombre }}
                            @if(!$loop->last)
                              -
                            @endif
                          @endforeach)
                        </small>
                      </span>
                    </h5>
                  </a>
                </div>
              </a>
            </p>

            <p>
              <span class="text-muted">Personas en cola:</span>
              <ol>
                @foreach ($registro->cola as $col)
                  <li>
                    <div class="d-flex">
                      <form action="{{ route('admin.cola.delete', [
                        $registro->libro->id,
                        $col->persona->id
                      ]) }}" method="POST">
                        @csrf
                        @method('delete')
                        <i class="fa fa-xs fa-trash text-danger mr-2"
                           style="cursor: pointer"
                           onclick="borrarPersona(event)">
                        </i>
                      </form>
                      <a href="{{ route('admin.personas.show', $col->persona->id) }}" class="text-reset">
                        {{ $col->persona->nombre }}
                      </a>
                    </div>
                  </li>
                @endforeach
              </ol>
            </p>
          </div>
        </div>

        <form action="{{ route('admin.cola.limpiar', $registro->libro->id ) }}" method="POST">
          @csrf
          @method('delete')
          <button class="btn btn-sm btn-outline-danger" onclick="limpiarCola(event)">
            <i class="fa fa-xs fa-trash"></i>
            Limpiar la cola de este libro
          </button>
        </form>

      </div>
    @endforeach

  </div>
@endsection
@push('scripts')
  <script>
    $('.nav-link-cola').addClass('active');
    function borrarPersona(ev) {
      ev.preventDefault()
      bootbox.confirm('¿Borrar esta persona de la cola?', confirma => {
        if (!confirma) return;
        $(ev.target).parent('form').submit();
      })
    }
    function limpiarCola(ev) {
      ev.preventDefault()
      bootbox.confirm('¿Limpiar la cola de este libro?', confirma => {
        if (!confirma) return;
        $(ev.target).parent('form').submit();
      })
    }
  </script>
@endpush