routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// SITIO
Route::group([
    'as' => 'sitio.',
    // 'middleware' => 'auth',
], function() {

    Route::get('/', 'SitioController@index')->name('index');
    Route::get('/offline', 'SitioController@offline')->name('offline');
    Route::get('/prestamos', 'SitioController@prestamos')->name('prestamos');
});

// PRESTAMOS
Route::group([
    'as' => 'prestamos.',
    'prefix' => 'prestamos',
    'middleware' => 'auth',
], function() {

    Route::get('create', 'PrestamoController@create')->name('create');
    Route::post('store', 'PrestamoController@store')->name('store');
});

// ADMIN
Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
], function() {

    Route::get('', 'AdminController@index')->name('index');

    // ADMIN LIBROS
    Route::group([
        'prefix' => 'libros',
        'as' => 'libros.',
    ], function() {

        Route::get('', 'LibroController@index')->name('index');
        Route::get('create', 'LibroController@create')->name('create');
        Route::post('', 'LibroController@store')->name('store');
        Route::get('{id}/edit', 'LibroController@edit')->name('edit');
        Route::put('{id}', 'LibroController@update')->name('update');
        Route::get('{id}', 'LibroController@show')->name('show');
        Route::delete('{id}', 'LibroController@destroy')->name('destroy');
    });

    // ADMIN AUTORES
    Route::group([
        'prefix' => 'autores',
        'as' => 'autores.',
        'middleware' => 'auth',
    ], function() {

        Route::get('', 'AutorController@index')->name('index');
        Route::get('create', 'AutorController@create')->name('create');
        Route::post('', 'AutorController@store')->name('store');
        Route::get('{id}/edit', 'AutorController@edit')->name('edit');
        Route::put('{id}', 'AutorController@update')->name('update');
        Route::get('{id}', 'AutorController@show')->name('show');
        Route::delete('{id}', 'AutorController@destroy')->name('destroy');
    });

    // ADMIN PERSONAS
    Route::group([
        'prefix' => 'personas',
        'as' => 'personas.',
        'middleware' => 'auth',
    ], function() {

        Route::get('', 'PersonaController@index')->name('index');
        Route::get('create', 'PersonaController@create')->name('create');
        Route::post('', 'PersonaController@store')->name('store');
        Route::get('{id}/edit', 'PersonaController@edit')->name('edit');
        Route::put('{id}', 'PersonaController@update')->name('update');
        Route::get('{id}', 'PersonaController@show')->name('show');
        Route::delete('{id}', 'PersonaController@destroy')->name('destroy');
    });

    // ADMIN COLA
    Route::group([
        'prefix' => 'cola',
        'as' => 'cola.',
    ], function() {

        Route::get('', 'ColaController@index')->name('index');
        Route::post('', 'ColaController@store')->name('store');
        Route::delete('{idLibro}/{idPersona}', 'ColaController@delete')->where([
                                                                           'idLibro' => '[0-9]+',
                                                                           'idPersona' => '[0-9]+',
                                                                       ])->name('delete');
        Route::delete('{idLibro}/limpiar', 'ColaController@limpiarCola')->name('limpiar');
    });
});

// API
Route::group([
    'prefix' => 'api',
], function() {

    // API PRESTAMOS
    Route::group([
        'prefix' => 'prestamos',
    ], function() {

        // Ajax
        Route::get('pendientes', 'PrestamoController@apiPendientes');
        Route::put('{id}', 'PrestamoController@apiUpdate');
        Route::delete('{id}', 'PrestamoController@apiDelete');

        Route::put('{id}/marcar-entregado', 'PrestamoController@apiMarcarEntregado');
    });

    // API AUTORES
    Route::group([
        'prefix' => 'autores',
        'namespace' => 'Admin',
    ], function() {

        // Ajax
        Route::get('todos', 'AutorController@apiTodos');

    });
});


Auth::routes();

resources/views/admin/autores/create.blade.php
@extends('admin.layout')
@section('titulo', 'Crear nuevo Autor')
@section('contenido_admin')
  <div class="container my-3">

    <h1 class="text-center">Crear nuevo Autor</h1>

    <form action="{{ route('admin.autores.store') }}"
          method="POST"
          x-data="{ submitting: false }"
          @submit="submitting = true">

      @csrf

      <div class="form-group">
        <label>Nombre:</label>

        <input class="form-control"
               type="text"
               name="nombre"
               value="{{ old('nombre') ?? '' }}"
               placeholder="Nombre del autor"
               required>

        @if ($errors->has('nombre'))
          <div class="alert alert-danger">
            {{ $errors->first('nombre') }}
          </div>
        @endif
      </div>


      @include('includes.botones-submit')

      <div class="d-flex justify-content-center mt-2">

        <button type="submit"
                class="btn btn-primary mr-2 d-block"
                :disabled="submitting"
                @click="$refs.aCrearLibro.removeAttribute('disabled')">
          <i class="fa fa-save"></i>
          Guardar e ir a "Crear Libro"
          <span x-show="submitting">@include('includes.spinner')</span>
        </button>

        <!-- este input indica si redirige a "Crear nuevo Libro" -->
        <input type="hidden" name="crear-para-libro" value="true" x-ref="aCrearLibro" disabled>

      </div>

    </form>
  </div>
@endsection
@push('scripts')
  <script>
    $('.nav-link-autores').addClass('active');
  </script>
@endpush

resources/views/admin/autores/edit.blade.php
@extends('admin.layout')
@section('titulo', 'Editar Autor')
@section('contenido_admin')
  <div class="container my-3">

    <h1 class="text-center">Editar Autor</h1>

    <form action="{{ route('admin.autores.update', $autor->id) }}"
          method="POST"
          x-data="{ submitting: false }"
          @submit="submitting = true">

      @csrf
      @method('put')

      <div class="form-group">
        <label>Nombre:</label>

        <input class="form-control"
               type="text"
               name="nombre"
               placeholder="Nombre del autor"
               value="{{ old('nombre') ?? $autor->nombre}}"
               required>

        @if ($errors->has('nombre'))
          <div class="alert alert-danger">
            {{ $errors->first('nombre') }}
          </div>
        @endif

      </div>


      @include('includes.botones-submit')

    </form>
  </div>
@endsection
@push('scripts')
  <script>
    $('.nav-link-autores').addClass('active');
  </script>
@endpush

resources/views/admin/autores/index.blade.php
@extends('admin.layout')
@section('titulo', 'Administrar Autores')
@section('contenido_admin')
  <div class="container my-3">

    <h1 class="text-center">Listado de Autores</h1>

    <div class="text-center">
      <a class="btn btn-sm btn-primary" href="{{ route('admin.autores.create') }}">
        <i class="fa fa-plus-circle"></i>
        Agregar un nuevo Autor
      </a>
    </div>

    @foreach($autores as $autor)
      <div class="my-3 border rounded p-1">


        <div class="d-flex justify-content-between align-items-center">
          <h4 class="my-0">{{ $autor->nombre }}</h4>

          <div class="ml-1" style="white-space: nowrap;">
            <a href="{{ route('admin.autores.show', $autor->id) }}"
               title="Ver este elemento"
               class="text-success mr-2">
              <i class="fa fa-eye"></i>
            </a>

            <a href="{{ route('admin.autores.edit', $autor->id) }}"
               title="Editar este elemento"
               class="text-info">
              <i class="fa fa-edit"></i>
            </a>
          </div>
        </div>

      </div>
    @endforeach


    <div class="d-flex justify-content-center my-5">
      {{ $autores->links() }}
    </div>
  </div>
@endsection
@push('scripts')
  <script>
    $('.nav-link-autores').addClass('active');
  </script>
@endpush

resources/views/admin/autores/show.blade.php
@extends('admin.layout')
@section('titulo', 'Ver Autor')
@section('contenido_admin')
  <div class="container my-3">

    <h1 class="text-center">Ver Autor</h1>

    <div class="d-flex justify-content-center">
      <form action="{{ route('admin.autores.destroy', $autor->id) }}"
            method="POST"
            class="mr-3">
        @method('delete')
        @csrf

        <a class="text-danger"
           title="Eliminar este elemento"
           onclick="eliminar(event)"
           href="#">
           <i class="fa fa-trash"></i>
        </a>
      </form>

      <a class="text-info"
         title="Editar este elemento"
         href="{{ route('admin.autores.edit', $autor->id) }}">
        <i class="fa fa-edit"></i>
      </a>
    </div>

    <hr>

    <span class="text-muted">Nombre:</span>
    <h4 class="my-0">{{ $autor->nombre }}</h4>

    <div class="d-flex justify-content-center my-5">
      <a class="btn btn-sm btn-secondary"
         href="{{ route('admin.autores.index') }}">
        Ir al índice de autores
      </a>
    </div>
  </div>
@endsection
@push('scripts')
  <script>
    $('.nav-link-autores').addClass('active');

    function eliminar(ev) {
      ev.preventDefault();

      bootbox.confirm('¿Desea eliminar este elemento?', (confirma) => {
        if (!confirma) return;

        ev.target.closest('form').submit();
      });
    }
  </script>
@endpush