routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// SITIO
Route::group([
    'as' => 'sitio.',
    // 'middleware' => 'auth',
], function() {

    Route::get('/', 'SitioController@index')->name('index');
    Route::get('/offline', 'SitioController@offline')->name('offline');
    Route::get('/prestamos', 'SitioController@prestamos')->name('prestamos');
});

// PRESTAMOS
Route::group([
    'as' => 'prestamos.',
    'prefix' => 'prestamos',
    'middleware' => 'auth',
], function() {

    Route::get('create', 'PrestamoController@create')->name('create');
    Route::post('store', 'PrestamoController@store')->name('store');
});

// ADMIN
Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
], function() {

    Route::get('', 'AdminController@index')->name('index');

    // ADMIN LIBROS
    Route::group([
        'prefix' => 'libros',
        'as' => 'libros.',
    ], function() {

        Route::get('', 'LibroController@index')->name('index');
        Route::get('create', 'LibroController@create')->name('create');
        Route::post('', 'LibroController@store')->name('store');
        Route::get('{id}/edit', 'LibroController@edit')->name('edit');
        Route::put('{id}', 'LibroController@update')->name('update');
        Route::get('{id}', 'LibroController@show')->name('show');
        Route::delete('{id}', 'LibroController@destroy')->name('destroy');
    });

    // ADMIN AUTORES
    Route::group([
        'prefix' => 'autores',
        'as' => 'autores.',
        'middleware' => 'auth',
    ], function() {

        Route::get('', 'AutorController@index')->name('index');
        Route::get('create', 'AutorController@create')->name('create');
        Route::post('', 'AutorController@store')->name('store');
        Route::get('{id}/edit', 'AutorController@edit')->name('edit');
        Route::put('{id}', 'AutorController@update')->name('update');
        Route::get('{id}', 'AutorController@show')->name('show');
        Route::delete('{id}', 'AutorController@destroy')->name('destroy');
    });

    // ADMIN PERSONAS
    Route::group([
        'prefix' => 'personas',
        'as' => 'personas.',
        'middleware' => 'auth',
    ], function() {

        Route::get('', 'PersonaController@index')->name('index');
        Route::get('create', 'PersonaController@create')->name('create');
        Route::post('', 'PersonaController@store')->name('store');
        Route::get('{id}/edit', 'PersonaController@edit')->name('edit');
        Route::put('{id}', 'PersonaController@update')->name('update');
        Route::get('{id}', 'PersonaController@show')->name('show');
        Route::delete('{id}', 'PersonaController@destroy')->name('destroy');
    });

    // ADMIN COLA
    Route::group([
        'prefix' => 'cola',
        'as' => 'cola.',
    ], function() {

        Route::get('', 'ColaController@index')->name('index');
        Route::post('', 'ColaController@store')->name('store');
        Route::delete('{idLibro}/{idPersona}', 'ColaController@delete')->where([
                                                                           'idLibro' => '[0-9]+',
                                                                           'idPersona' => '[0-9]+',
                                                                       ])->name('delete');
        Route::delete('{idLibro}/limpiar', 'ColaController@limpiarCola')->name('limpiar');
    });
});

// API
Route::group([
    'prefix' => 'api',
], function() {

    // API PRESTAMOS
    Route::group([
        'prefix' => 'prestamos',
    ], function() {

        // Ajax
        Route::get('pendientes', 'PrestamoController@apiPendientes');
        Route::put('{id}', 'PrestamoController@apiUpdate');
        Route::delete('{id}', 'PrestamoController@apiDelete');

        Route::put('{id}/marcar-entregado', 'PrestamoController@apiMarcarEntregado');
    });

    // API AUTORES
    Route::group([
        'prefix' => 'autores',
        'namespace' => 'Admin',
    ], function() {

        // Ajax
        Route::get('todos', 'AutorController@apiTodos');

    });
});


Auth::routes();

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    @laravelPWA

    <title>{{ config('app.name', 'Laravel') }} - @yield('titulo')</title>

    <!-- Fonts -->
    <!-- <link rel="dns&#45;prefetch" href="//fonts.gstatic.com"> -->
    <!-- <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet"> -->

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/fa-all.css') }}">
    @stack('styles')
</head>
<body>
  <div id='goTop'></div>
  @include('layouts.header')

  @if (session('feedback'))
    @include('includes.feedback', ['feedback' => session('feedback')])
  @endif

  <main class="pt-4 pb-5 mb-5">
      @yield('contenido')
  </main>

  @include('layouts.navegacion')


  <!-- Scripts -->
  <script src="{{ mix('js/app.js') }}"></script>
  <script src="{{ asset('js/alpine.js') }}"></script>
  <script src="{{ asset('js/jquery.gotop.min.js') }}"></script>
  @stack('scripts')
</body>
</html>

resources/views/layouts/header.blade.php
<div class="header bg-secondary static-top">
  <a href="{{ route('sitio.index') }}">
    <img src="{{ asset('images/logotexto.png') }}"
         alt="Logo Iglesia SPEV"
         height="50">
  </a>
</div>

resources/views/layouts/navegacion.blade.php
<div class="navegacion fixed-bottom bg-secondary align-items-end space-between">
  <a href="javascript:history.go(-1)"
     class="btn-navegacion"
     title="Ir Atrás">
    <i class="fa fa-lg fa-arrow-circle-left"></i>
  </a>

  <a href="{{ route('admin.libros.index') }}"
     class="btn-navegacion"
     title="Ver catálogo de libros">
    <i class="fa fa-lg fa-book"></i>
  </a>

  @auth
      <a href="{{ route('sitio.prestamos') }}"
         class="btn-navegacion"
         title="Ver prestamos">
        <i class="fa fa-lg fa-book-reader"></i>
      </a>

    <a href="{{ route('admin.index') }}"
       class="btn-navegacion"
       title="Ir a Administración">
      <i class="fa fa-lg fa-tools"></i>
      @if ($LibroDisponibleConCola)
        <span class="text-success h4"><b>*</b></span>
      @endif
    </a>
  @endauth

  @auth
    <a href="{{ route('prestamos.create') }}"
       class="btn-navegacion"
       title="Nuevo Préstamo">
      <i class="fa fa-lg fa-plus"></i>
    </a>
  @endauth

  @guest
    <a href="{{ route('login') }}"
       class="btn-navegacion"
       title="Inicia sesión">
      <i class="fa fa-lg fa-sign-in-alt"></i>
    </a>
  @endguest
</div>